<header class="admin-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<?= $requestUrl ?>/admin">Administration</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav mr-0">
                <li class="nav-item active">
                    <a href="<?= $requestUrl ?>/admin/addSeance">Ajouter une séance</a>
                </li>
                <li class="nav-item">
                    <a href="<?= $requestUrl ?>/admin/addFilm">Ajouter un film</a>
                </li>
                <li class="nav-item">
                    <a href="<?= $requestUrl ?>/admin/background">Modifier l'arriere plan</a>
                </li>
                <li class="nav-item">
                    <a href="<?= $requestUrl ?>/admin/logout" id="disconnect">Se déconnecter</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main id="background-page">
    <h2>Choisissez votre arrière-plan</h2>
    <form action="" method="post" enctype="multipart/form-data">
        <h2>Upload Fichier</h2>
        <label for="fileUpload">Fichier:</label>
        <input type="file" name="image" id="fileUpload">
        <input type="submit" name="submit" value="Upload">
        <p><strong>Note:</strong> Seuls les formats .jpg, .jpeg et .png sont autorisés</p>
        <?php if(isset($error['format'])){echo "<p class='text-danger'>".$error["format"]."<p>";} ?>
        <?php if(isset($error['size'])){echo "<p class='text-danger'>".$error['size']."<p>";} ?>
        <?php if(isset($error['existe'])){echo "<p class='text-danger'>".$error['existe']."<p>";} ?>
    </form>

</main>